title: Ongi etorri denoi!
author: andonirekondo
email: rekondo.andoni@opendeusto.es
description: > # this means to ignore newlines until "baseurl:"
  Ongi etorri guztioi orrialde honetara, bertan mota askotako edukiak topatuko dituzue!

# social links
twitter_username: a_rekondo # NO incluyas el carácter @ character, ¡o la compilación fallará!
github_username:  andonirekondo # NO incluyas el carácter @ character, ¡o la compilación fallará!

show_excerpts: false # cámbialo a false para eliminar los extractos de la página principal
theme: minima
